### PR TITLE
Fixing a few minor typos

### PR DESCRIPTION
**Pull request by slalFe**

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Thx, if you fix the translation you should read this: https://docs.squidex.io/01-getting-started/contributing-and-developing/translating

**Comment by SebastianStehle** [comment]
I would like to merge it, but you have to make the modifications in the sources folder and then run the translator.

**Comment by SebastianStehle** [comment]
I have merged it manually.

**Comment by slalFe** [comment]
Thanks and apologies for not finalising it myself, just had some other work that took priority.

**Pull request closed without merging**
