### PR TITLE
localization part 1

### PR DESCRIPTION
**Pull request by dborovsky**

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Hi, I have decided not to localize the script names, it is by purpose.

**Comment by dborovsky** [comment]
> You should also read this: https://docs.squidex.io/01-getting-started/contributing-and-developing/translating
sure, i've already read this.

**Comment by SebastianStehle** [comment]
But then you do not understand or the article is badly written. Because you should not change the translation files directly. Only change the files under source folder and then  run the translator.

**Comment by dborovsky** [comment]
@SebastianStehle 
- To update localize files must I change corresponding files in folder backend/i18n/source
- Run the translate.bat or translate.sh

Correct?

**Comment by SebastianStehle** [comment]
Yes, thats correct.

If you are not a native speaker, you should not translate these languages. There are other people and customers who take care about NL and IT

**Comment by dborovsky** [comment]
> Hi, I have decided not to localize the script names, it is by purpose.

I returned back script without localization. 

I can't find any labels without localization. Could you show me this? 
Somewhere is no translation because localization key has value with english. Need translate to It and ND, but i am no native speaker.

**Comment by SebastianStehle** [comment]
I think there is nothing to translate at the moment. Perhaps you misunderstood the original task.

**Pull request closed without merging**
