### PR TITLE
Fixes for Cosmos Db compatibility

### PR DESCRIPTION
**Pull request by pushrbx**
Changed some of the aggregate queries to query in to memory then do the aggregation operation on the collection of items. I'll commit more to this pull request as I find more not working queries. Don't merge it yet please. 
Tries to fix issue #44

### CODE REVIEW

**Comment by SebastianStehle** [comment]
It would be much easier to assume that there will not be more than 2 Billion users and just use a Count() instead ;)

Retrieving all users just to get the count is very expensive ;)

**Comment by pushrbx** [comment]
I'll try to come up with another solution this weekend.  :)

**Comment by SebastianStehle** [comment]
I have just tested Any() and Count() ... works fine, but the problem is the EventStore :(

**Comment by SebastianStehle** [comment]
I close this pull request for now, because I need to find a solution for the EventStore first. Perhaps just sql? ;)

**Pull request closed without merging**
