### PR TITLE
Pending should be false when changing status

### PR DESCRIPTION
**Pull request by Avd6977**
Fixing a weird state on content
1. Create and publish a content item
2. Make a pending change
3. Select "Unpublish" and the pending data is still there.

If you're unpublished, you shouldn't be able to have a pending version.

### CODE REVIEW

**Comment by Avd6977** [comment]
You're right. We would need to sync the data and dataDraft in that scenario. Which you don't know if they would be approving or rejecting the pending changes. What are your thoughts on it?

**Comment by SebastianStehle** [comment]
just an else?

```
protected void On(ContentStatusChanged @event)
        {
            ScheduleJob = null;

            Status = @event.Status;

            if (@event.Status == Status.Published)
            {
                Data = DataDraft;
            }
            else
            { 
                DataDraft = Data;
            }
            
            IsPending = false;
        }
```

**Comment by Avd6977** [comment]
Either that or hide the options from them and not allow them to change status without accepting or rejecting the changes. The else makes an assumption that they want to discard the changes.

**Comment by SebastianStehle** [comment]
Or we always set `Data = DataDraft` so you do not loose changes. Actually it does not really matter.

**Pull request merged**
