### PR TITLE
Adding selected Content to context form

### PR DESCRIPTION
**Pull request by Anders-Arnfast-CreunaDK**

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Because it does not get updated automatically when something is changed, would it not be better to name it "initialContent" or so.

**Comment by SebastianStehle** [comment]
There is also another one: https://github.com/Squidex/squidex/blob/master/frontend/app/features/content/shared/references/content-creator.component.ts

**Comment by Anders-Arnfast-CreunaDK** [comment]
Yes, i agree with the naming i'll change that, InitialContent makes sense, in regards to thttps://github.com/Squidex/squidex/blob/master/frontend/app/features/content/shared/references/content-creator.component.ts isn't it a pre-content component, i mean it looks like there isn't any content to add to the form context, or am i wrong?

**Comment by SebastianStehle** [comment]
Yes, you are right :D...but can you also change formContext to contentFormContext

**Comment by Anders-Arnfast-CreunaDK** [comment]
@SebastianStehle wouldn't it be a potential breaking change who people who might use it?

**Comment by SebastianStehle** [comment]
In general, because OnPush, it might be better to generate a new instance of the formContext...

e.g. with

this.contentFormContext = { ...this.contentFormContext, initialContent: content }

**Comment by Anders-Arnfast-CreunaDK** [comment]
@SebastianStehle  is that what you ment?

**Comment by SebastianStehle** [comment]
Sorry, I just meant this single field in the content-page.component  ... :( 

My fault

**Pull request merged**
