### PR TITLE
Feature/proxy forwarded host option

### PR DESCRIPTION
**Pull request by mhilgersom**
This PR uses the X-Forwarded-Host header to set the correct hostname in .Net Core when running behind a reverse proxy. 

Only when the X-Forwarded-Host field is present and the hostname matches the baseUrl property and the enableXForwardedHost option is enabled this header will be used.

With this PR setting the PublicOriging for IdentityServer might not be needed anymore.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Thank you very much. We should make it in a way so that is fully backwards compatible.

**Comment by mhilgersom** [comment]
I agree. I think we should remove the fixed PublicOrigin for IdentityServer and replace it with this method of using the X-Forwarded-Host header. 

This way it only affects users that set explicitly set this new option. And it will only be effective when the supplied X-Forward-Host header matches the hostname of the confugred baseUrl setting.

**Comment by SebastianStehle** [comment]
Will you take care about it?

**Comment by mhilgersom** [comment]
Yes. Busy with over project. Will fix asap.

**Comment by mhilgersom** [comment]
I've updated the PR and tested this one within our environment.

**Pull request merged**
