### PR TITLE
Fixed issue with unpublished content not being available for GraphQL

### PR DESCRIPTION
**Pull request by niklasise**
Fixed issue with unpublished content not being available for GraphQL queries. See https://support.squidex.io/t/unpublished-content-through-graphql/457 for more details.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Would be great to have a test for it.

**Comment by niklasise** [comment]
Aight, I'm on it :)

**Comment by niklasise** [comment]
...will probably do it tomorrow though since it's getting late and I have an early morning. Will let you now if I run into any problems

**Comment by SebastianStehle** [comment]
Great and thank you very much for your contribution :)

**Comment by niklasise** [comment]
No problem. Just glad I could contribute to such as good project!

Added a commit with a fix for when dataDraft was null, as well as two unit tests for the dataDraft property. Let me know what you think.

**Comment by SebastianStehle** [comment]
Thank you very much :)

**Pull request merged**
