### PR TITLE
Save Query box fixes

### PR DESCRIPTION
**Pull request by dsbegnoche**
Save Query box does not clear out last saved item when opening
Cancel button saves query

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Thank you. The "offical" way is to call form.submitCompleted({}) in this case.

**Comment by SebastianStehle** [comment]
Can you fix it?

Btw: Can you write me a testimonial: https://support.squidex.io/t/request-for-testimonials/165 ?

**Comment by dsbegnoche** [comment]
Yes. Will get that updated in a few.

**Comment by dsbegnoche** [comment]
Updated with correct form reset.

**Pull request merged**
